name:                staticfriend
version:             0.1.0.0
github:              "nineonine/staticfriend"
license:             BSD3
author:              "nineonine"
maintainer:          "mail4chemik@gmail.com"
copyright:           "2021 nineonine"

extra-source-files:
- README.md
- ChangeLog.md
description:         Please see the README on GitHub at <https://github.com/nineonine/staticfriend#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  staticfriend-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - staticfriend

tests:
  staticfriend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - staticfriend
